version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirement.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_packagedoordash.zip .
      - cd ..
      - zip -g deployment_packagedoordash.zip lambda_function.py
      - zip -g deployment_packagedoordash.zip .env
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_packagedoordash.zip s3://lambda-builds-zip29aug24/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name Doordash_lambda --s3-bucket lambda-builds-zip29aug24 --s3-key deployment_packagedoordash.zip
      - echo "Deployment complete!"